debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/certs/server.crt"
      keyFile = "/etc/certs/server.key"

## Dynamic configuration
# Testing from https://doc.traefik.io/traefik/routing/routers/
# THIS ALMOST works, but redirs to /hub/jupyter
# [http]
#   [routers]
#     [my-router]
#       rule="Path(`/jupyter`)"
#       service="jupyterhub"


[docker]
domain = "docker.local"
watch = true

[api]
  [api.statistics]
    recentErrors = 10
